
name: auto-run-test-many-projects-script-on-testrunner

on: [push, pull_request]

jobs:
  manyProjLegacyTest1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B

      - name: Test 1st set of projects
        run: set -o pipefail ; bash scripts/test-many-projects.sh scripts/idfProjects1.csv idflakies-legacy |& tee -a scripts/GeneralLogs.log

      - name: Move Logs file into the ARTIFACTS folder
        if: always()
        run: mv scripts/GeneralLogs.log scripts/testing-script-results/ARTIFACTS/

      - name: Save all relevant files
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: test-many-projects_ARTIFACT_1
         path: scripts/testing-script-results/ARTIFACTS

  manyProjLegacyTest2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B

      - name: Test 2nd set of projects
        run: set -o pipefail ; bash scripts/test-many-projects.sh scripts/idfProjects2.csv idflakies-legacy |& tee -a scripts/GeneralLogs.log

      - name: Move Logs file into the ARTIFACTS folder
        if: always()
        run: mv scripts/GeneralLogs.log scripts/testing-script-results/ARTIFACTS/

      - name: Save all relevant files
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: test-many-projects_ARTIFACT_2
         path: scripts/testing-script-results/ARTIFACTS

  manyProjLegacyTest3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B

      - name: Test 3rd set of projects
        run: set -o pipefail ; bash scripts/test-many-projects.sh scripts/idfProjects3.csv idflakies-legacy |& tee -a scripts/GeneralLogs.log

      - name: Move Logs file into the ARTIFACTS folder
        if: always()
        run: mv scripts/GeneralLogs.log scripts/testing-script-results/ARTIFACTS/

      - name: Save all relevant files
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: test-many-projects_ARTIFACT_3
         path: scripts/testing-script-results/ARTIFACTS

  manyProjLegacyTest4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B

      - name: Test 4th set of projects
        run: set -o pipefail ; bash scripts/test-many-projects.sh scripts/idfProjects4.csv idflakies-legacy |& tee -a scripts/GeneralLogs.log

      - name: Move Logs file into the ARTIFACTS folder
        if: always()
        run: mv scripts/GeneralLogs.log scripts/testing-script-results/ARTIFACTS/

      - name: Save all relevant files
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: test-many-projects_ARTIFACT_4
         path: scripts/testing-script-results/ARTIFACTS

