# This is a basic workflow to help you get started with Actions

name: auto-run-manyConfigs-script

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  manyConfigsTest1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # timeout-minutes: 4320
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B

      - name: Test set of projects
        run: set -o pipefail ; bash scripts/manyConfigs.sh scripts/testExpectations.csv |& tee -a scripts/GeneralLogs.log

      - name: Move Logs file into the Artifact folder
        if: always()
        run: mv scripts/GeneralLogs.log scripts/MC-script-results/ARTIFACTS/

      - name: Save all relevant files
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: artifact_1
         path: scripts/MC-script-results/ARTIFACTS

